version = 0.1
[default.deploy.parameters]
stack_name = "cloudproj"
resolve_s3 = true
s3_prefix = "cloudproj"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "SourceLocation=\"https://github.com/slneha/text_to_speech.git\" SourceVersion=\"\""
image_repositories = []
